# services:
#   dev:
#     container_name: nestjs_api_dev
#     image: nestjs-api-dev:1.0.0
#     build:
#       context: .
#       target: development
#       dockerfile: ./Dockerfile
#     ports:
#       - 8000:8000
#     depends_on:
#       - postgres
#     env_file:
#       - .env
#     environment:
#       DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     restart: unless-stopped
#     command: npm run start:migrate

#   prod:
#     container_name: nestjs_api_prod
#     image: nestjs-api-prod:1.0.0
#     build:
#       context: .
#       target: production
#       dockerfile: ./Dockerfile
#     ports:
#       - 8000:8000
#     depends_on:
#       - postgres
#     env_file:
#       - .env
#     environment:
#       DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     restart: unless-stopped
#     command: npm run start:prod

#   postgres:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     ports:
#       - '5432:5432'
#     env_file:
#       - .env
#     volumes:
#       - nest-postgres:/var/lib/postgresql/data
# volumes:
#   nest-postgres:
