name: Continous deployment

on:
  pull_request:
  push:
    branches:
      - main
      - production

jobs:
  
  test:
    name: Run unit - e2e tests and lint code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Tests
        run: echo "RUNNING TEST"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Lint Check
        run: echo "RUNNING LINT /"