name: stop workflow
# Trigger jobs only when 
# - PR is created 
# - Merge into main
# - Merge into production
on:
  push:
    branches:
      - main
      - production
  pull_request:
jobs:
  cancel:
    name: 'Cancel Other Workflow'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
